make staging up to date with dev as staging is not updated and behind dev and main
Vamania69/product-app pull request #6
Opened 2023-09-26 17:46 UTC by Vamania69

2023-09-28 16:40 UTC, AnadiSharma007 requested changes

2023-09-28 16:40 UTC, AnadiSharma007 commented on src/components/Categories.tsx
> +        const response = await axios.get(`${BASE_URL}/categories`);
move BASE_URL to .env.local file

2023-09-28 16:40 UTC, AnadiSharma007 commented on src/components/Hero.tsx
> +    <Image className='min-h-full min-w-full' src="/Hero.jpg" alt="hero img" height={200} width={100}/>
If you are using static images. Import them as a module and then use it. Like 
`
import heroImage from '/hero.jpg'
<Image className='min-h-full min-w-full' src={heroImage} alt="hero img" height={200} width={100}/>
`

2023-09-28 16:40 UTC, AnadiSharma007 commented on src/pages/category/[category].tsx
> +          `${BASE_URL}/products?categoryId=${categoryId}`
move to .env.local file

2023-09-28 16:40 UTC, AnadiSharma007 commented on src/pages/category/[category].tsx
> +              return <Card key={product.productId} productDetails={product} />;
add ? in product.productId

2023-09-28 16:40 UTC, AnadiSharma007 commented on src/utils/getImageUrls.ts
> +  const ImagesUrl = productImages.map((image, i) => {
add ?.

2023-10-03 04:34 UTC, Vamania69 commented on src/components/Categories.tsx
> +        const response = await axios.get(`${BASE_URL}/categories`);
sir i have tried multiple way to handle the error but still the BASE_URL remains undefined also tried after removing the space in the env file

2023-10-03 05:08 UTC, Vamania69 commented on src/pages/category/[category].tsx
> +          `${BASE_URL}/products?categoryId=${categoryId}`
similary issuse it consistenty hints on http://localhost:3000/category/undefined/products.....

2023-10-31 16:48 UTC, merged